Fix composer install

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -51,11 +51,21 @@ shared-code: &shared-code
     - run:
         name: Install comopser
         command: |
+          EXPECTED_SIGNATURE="$(wget -q -O - https://composer.github.io/installer.sig)"
           php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"
-          php -r "copy('https://composer.github.io/installer.sig', 'installer.sig');"
-          php -r "if (hash_file('sha384', 'composer-setup.php') === file_get_contents('installer.sig')) { echo 'Installer verified'; } else { echo 'Installer corrupt'; unlink('composer-setup.php'); } echo PHP_EOL;"
-          php composer-setup.php --install-dir=/usr/bin --filename=composer
-          php -r "unlink('composer-setup.php');"
+          ACTUAL_SIGNATURE="$(php -r "echo hash_file('sha384', 'composer-setup.php');")"
+
+          if [ "$EXPECTED_SIGNATURE" != "$ACTUAL_SIGNATURE" ]
+          then
+              >&2 echo 'ERROR: Invalid installer signature'
+              rm composer-setup.php
+              exit 1
+          fi
+
+          php composer-setup.php --quiet --install-dir=/usr/bin --filename=composer
+          RESULT=$?
+          rm composer-setup.php
+          exit $RESULT
 
     - run:
         name: Update composer
